# ganti ke Project Ref asli kamu
project_id = "zblqhrdihjqgbryyhzug"

[auth]
minimum_password_length = 8
password_requirements = "lower_upper_letters_digits"
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
secure_password_change = true
enable_confirmations = false   # dev lokal boleh off
otp_length = 6
otp_expiry = 3600

[auth.rate_limit]
email_sent = 5
sign_in_sign_ups = 15
token_verifications = 20
anonymous_users = 0

[functions.healthcheck]
enabled = true
verify_jwt = false
import_map = "./functions/healthcheck/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/healthcheck/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/healthcheck/*.html" ]

