name: Build AAB

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# root-level (bukan di bawah `workflow_dispatch`)
permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 1) Pastikan jalur build sehat: debug APK harus sukses
      - name: Build Debug APK
        run: ./gradlew --no-daemon --stacktrace :app:assembleDebug

      # 2) Release AAB tanpa lint (hindari lint-vital memblokir CI)
      - name: Build Release AAB (skip lint)
        run: ./gradlew --no-daemon --stacktrace :app:bundleRelease -x lint

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-aab
          path: app/build/outputs/bundle/release/*.aab

      - name: Upload ProGuard mapping
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mapping
          path: app/build/outputs/mapping/release/mapping.txt
          if-no-files-found: ignore
